openapi: 3.0.1
info:
  title: Personal Management API
  version: 1.0.0
servers:
  - url: localhost:8080/
paths:
  /details:
    get:
      summary: GetDetails
      description: Get the details
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getDetailsResp'
                
  /users:
    get:
      summary: GetUsers
      description: Get users
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getUsersResp'
                
  /users/{id}:
    get:
      summary: GetUserByID
      description: Get user by ID
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getUserResp'

components:
  schemas:
    getDetailsResp:
      type: object
      description: Get Details Response object
      properties:
        activity_name:
          type: string
        start_time:
          type: string
        end_time:
          type: string
        priority:
          type: integer
          format: int32
          
    getUsersResp:
      type: object
      description: Get Users response object
      properties:
        user_data:
          type: array
          description: Individual user data object
          items:
            $ref: '#/components/schemas/getUserResp'
                
    getUserResp:
      type: object
      description: Individual user data object
      properties:
        name:
          type: string
        id:
          type: string
        group:
          type: string
